#ifndef TKOMSIUNITS_CODE_OBJECTS_INSTR_RESULT_H_INCLUDED
#define TKOMSIUNITS_CODE_OBJECTS_INSTR_RESULT_H_INCLUDED

enum class InstrResult {
    NORMAL,
    RETURN,
    BREAK,
    CONTINUE
};

#endif // TKOMSIUNITS_CODE_OBJECTS_INSTR_RESULT_H_INCLUDED
